export const ADD_NOTE = "ADD_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const CHANGE_NOTE = "CHANGE_NOTE";

export const ADD_NOTE_TO_ARCHIVE = "AADD_NOTE_TO_ARCHIVED_NOTE";
export const DELETE_NOTE_FROM_ARCHIVE = "DELETE_NOTE_FROM_ARCHIVE";
export const RESTORE_NOTE_FROM_ARCHIVE = "RESTORE_NOTE_FROM_ARCHIVE";
